#!/bin/sh
set -eu

root=${S_PROJECT_ROOT:-$(CDPATH= cd -- "$(dirname -- "$0")/../.." && pwd)}
report=${BOOTSTRAP_ROOT_CANDIDATE_REPORT:-"$root/.bootstrap/modular/bootstrap-root-candidate-audit.txt"}

mkdir -p "$(dirname -- "$report")"

closure=${STAGE0_CLOSURE:-"$root/.bootstrap/modular/canonical-closure.txt"}
closure_count=0
if [ -f "$closure" ]; then
    closure_count=$(wc -l <"$closure" | tr -d ' ')
fi

has_selfhost_source=NO
[ -f "$root/src/cmd/compile/selfhost/compiler.s" ] && has_selfhost_source=YES

has_seed=NO
[ -x "$root/bin/s_seed" ] && has_seed=YES

has_seed_ir_aot=NO
if rg -q -e '--emit-aot|--emit-aot-obj|--emit-standalone-amd64|--emit-bin|--link-ir' "$root/makefile" "$root/src/cmd/compile/seed" 2>/dev/null; then
    has_seed_ir_aot=YES
fi

has_generated_c_stage0=NO
if [ -f "$root/.bootstrap/modular/s_modular-stage1.c" ] || rg -q 'write_stage1_c' "$root/src/cmd/compile/stage0/stage0.c" 2>/dev/null; then
    has_generated_c_stage0=YES
fi

has_checked_in_ir=NO
if find "$root" -path "$root/.git" -prune -o -path "$root/.bootstrap" -prune -o -name '*.ir' -type f -print | grep -q .; then
    has_checked_in_ir=YES
fi

has_prebuilt_binary=NO
if [ -x "$root/bin/s" ] || [ -x "$root/bin/s_compiler" ] || [ -x "$root/bin/s_darwin_arm64" ]; then
    has_prebuilt_binary=YES
fi

has_reduced_slice=NO
if rg -q 'bootstrap-slice|slice[0-9]' "$root/makefile" "$root/src/cmd/dist" 2>/dev/null; then
    has_reduced_slice=YES
fi

has_convergence_gate=NO
if rg -q 'stage2.*stage3|Stage2.*Stage3|bootstrap-convergence|cmp .*stage2.*stage3|canonical-selfhost-convergence' \
    "$root/makefile" "$root/misc/scripts" "$root/src/cmd/compile" 2>/dev/null; then
    has_convergence_gate=YES
fi

has_canonical_modular_consumption=NO
if [ -f "$root/.bootstrap/modular/stage1-canonical-entry-linkage-report.txt" ] && \
   grep -qx 'stage1-canonical-entry-linkage=PROVEN' "$root/.bootstrap/modular/stage1-canonical-entry-linkage-report.txt"; then
    has_canonical_modular_consumption=YES
fi

candidate_a_viability=PARTIAL
candidate_a_risk=medium
candidate_a_artifact=SOURCE
candidate_a_regen='s_seed -> selfhost/compiler.s -> stage2/stage3 convergence'
candidate_a_reason='historical selfhost chain exists, but target is selfhost/compiler.s rather than 37-file canonical modular closure'
if [ "$has_selfhost_source" != YES ]; then
    candidate_a_viability=UNKNOWN
    candidate_a_risk=unknown
    candidate_a_reason='selfhost/compiler.s source missing'
fi

candidate_b_viability=PARTIAL
candidate_b_risk=high
candidate_b_artifact=IR
candidate_b_regen='canonical compiler must regenerate bootstrap IR and compare semantic/artifact equivalence'
candidate_b_reason='seed IR/AOT exists, but canonical closure frontend/semantic consumption is not proven'
if [ "$has_seed" != YES ] || [ "$has_seed_ir_aot" != YES ]; then
    candidate_b_viability=UNKNOWN
    candidate_b_risk=unknown
    candidate_b_reason='seed executable or IR/AOT path missing'
fi

candidate_c_viability=PARTIAL
candidate_c_risk=medium
candidate_c_artifact=C
candidate_c_regen='canonical compiler emits reviewed bootstrap C, then byte/semantic equivalence check'
candidate_c_reason='generated C mechanism exists for current artifact stage, but it is metadata/artifact-only and not canonical compiler code'
if [ "$has_generated_c_stage0" != YES ]; then
    candidate_c_viability=UNKNOWN
    candidate_c_risk=unknown
    candidate_c_reason='no generated C bootstrap representation found'
fi

candidate_d_viability=UNKNOWN
candidate_d_risk=unknown
candidate_d_artifact=IR
candidate_d_regen='canonical compiler regenerates checked-in bootstrap IR with deterministic diff gate'
candidate_d_reason='checked-in bootstrap IR root not found outside build artifacts'
if [ "$has_checked_in_ir" = YES ]; then
    candidate_d_viability=PARTIAL
    candidate_d_risk=medium
    candidate_d_reason='IR artifacts exist in tree, but canonical provenance/reviewability is not proven'
fi

candidate_e_viability=PARTIAL
candidate_e_risk=high
candidate_e_artifact=BINARY
candidate_e_regen='trusted binary must be regenerated by canonical Stage2/Stage3 and provenance-attested'
candidate_e_reason='prebuilt binaries exist, but provenance and canonical convergence are not sufficient as root proof'
if [ "$has_prebuilt_binary" != YES ]; then
    candidate_e_viability=UNKNOWN
    candidate_e_risk=unknown
    candidate_e_reason='no prebuilt bootstrap binary found'
fi

candidate_f_viability=PARTIAL
candidate_f_risk=medium
candidate_f_artifact=SOURCE
candidate_f_regen='canonical compiler maintains reduced bootstrap slice with convergence against full canonical compiler'
candidate_f_reason='slice gates exist, but they target historical selfhost slices rather than a reduced canonical modular slice'
if [ "$has_reduced_slice" != YES ]; then
    candidate_f_viability=UNKNOWN
    candidate_f_risk=unknown
    candidate_f_reason='no reduced bootstrap slice evidence found'
fi

recommended_strategy='generated-bootstrap-representation-or-checked-in-bootstrap-ir'
recommended_artifact='C|IR'
root_regeneration_path='canonical Stage2/Stage3 regenerates root artifact; deterministic semantic/artifact equivalence required'
if [ "$candidate_c_viability" = PARTIAL ] && [ "$candidate_b_viability" = PARTIAL ]; then
    recommended_strategy='bounded-generated-bootstrap-artifact-using-existing-seed-ir-aot'
    recommended_artifact='C_OR_IR'
fi

{
    echo "bootstrap-root-candidate-audit"
    echo "canonical-closure-source-count=$closure_count"
    echo "canonical-closure-root=src/cmd/compile/modular_build_main.s"
    echo "bootstrap-root-semantic-authority=ALLOWED_IF_BOUNDED"
    echo "thin-bridge-semantic-authority=FORBIDDEN"
    echo "long-term-dual-semantic-authority=FORBIDDEN"
    echo "canonical-equivalence-question=can-root-produce-stage1-that-enters-canonical-authority-and-converges-through-stage2-stage3"
    echo "canonical-selfhost-convergence-gate=REQUIRED"
    echo "candidate=A-historical-selfhost-compiler"
    echo "  viability=$candidate_a_viability"
    echo "  risk=$candidate_a_risk"
    echo "  non-circular=YES"
    echo "  semantic-authority-source=src/cmd/compile/selfhost/compiler.s"
    echo "  trusted-code-size=large"
    echo "  canonical-equivalence=NOT_PROVEN"
    echo "  reproducibility=$has_convergence_gate"
    echo "  cross-platform-bootstrap=PARTIAL"
    echo "  artifact-reviewability=YES"
    echo "  stage1-generation-capability=PARTIAL"
    echo "  stage1-to-stage2-convergence=PARTIAL"
    echo "  eventual-root-removability=PARTIAL"
    echo "  recommended-root-artifact=$candidate_a_artifact"
    echo "  root-regeneration-path=$candidate_a_regen"
    echo "  reason=$candidate_a_reason"
    echo "candidate=B-existing-seed-ir-aot-artifacts"
    echo "  viability=$candidate_b_viability"
    echo "  risk=$candidate_b_risk"
    echo "  non-circular=YES"
    echo "  semantic-authority-source=src/cmd/compile/seed"
    echo "  trusted-code-size=large"
    echo "  canonical-equivalence=NOT_PROVEN"
    echo "  reproducibility=PARTIAL"
    echo "  cross-platform-bootstrap=PARTIAL"
    echo "  artifact-reviewability=PARTIAL"
    echo "  stage1-generation-capability=PARTIAL"
    echo "  stage1-to-stage2-convergence=NOT_PROVEN"
    echo "  eventual-root-removability=PARTIAL"
    echo "  recommended-root-artifact=$candidate_b_artifact"
    echo "  root-regeneration-path=$candidate_b_regen"
    echo "  reason=$candidate_b_reason"
    echo "candidate=C-generated-c-bootstrap-representation"
    echo "  viability=$candidate_c_viability"
    echo "  risk=$candidate_c_risk"
    echo "  non-circular=YES"
    echo "  semantic-authority-source=generator-provenance-required"
    echo "  trusted-code-size=medium"
    echo "  canonical-equivalence=REGENERATION_REQUIRED"
    echo "  reproducibility=PARTIAL"
    echo "  cross-platform-bootstrap=YES"
    echo "  artifact-reviewability=YES"
    echo "  stage1-generation-capability=PARTIAL"
    echo "  stage1-to-stage2-convergence=NOT_PROVEN"
    echo "  eventual-root-removability=YES_IF_REGENERATED_BY_CANONICAL"
    echo "  recommended-root-artifact=$candidate_c_artifact"
    echo "  root-regeneration-path=$candidate_c_regen"
    echo "  reason=$candidate_c_reason"
    echo "candidate=D-checked-in-bootstrap-ir"
    echo "  viability=$candidate_d_viability"
    echo "  risk=$candidate_d_risk"
    echo "  non-circular=YES"
    echo "  semantic-authority-source=artifact-provenance-required"
    echo "  trusted-code-size=medium"
    echo "  canonical-equivalence=REGENERATION_REQUIRED"
    echo "  reproducibility=YES_IF_DETERMINISTIC_IR"
    echo "  cross-platform-bootstrap=PARTIAL"
    echo "  artifact-reviewability=YES"
    echo "  stage1-generation-capability=PARTIAL"
    echo "  stage1-to-stage2-convergence=NOT_PROVEN"
    echo "  eventual-root-removability=YES_IF_REGENERATED_BY_CANONICAL"
    echo "  recommended-root-artifact=$candidate_d_artifact"
    echo "  root-regeneration-path=$candidate_d_regen"
    echo "  reason=$candidate_d_reason"
    echo "candidate=E-prebuilt-trusted-bootstrap-binary"
    echo "  viability=$candidate_e_viability"
    echo "  risk=$candidate_e_risk"
    echo "  non-circular=YES"
    echo "  semantic-authority-source=binary-provenance-required"
    echo "  trusted-code-size=opaque-large"
    echo "  canonical-equivalence=REGENERATION_REQUIRED"
    echo "  reproducibility=WEAK_UNTIL_REGENERATED"
    echo "  cross-platform-bootstrap=WEAK"
    echo "  artifact-reviewability=NO"
    echo "  stage1-generation-capability=PARTIAL"
    echo "  stage1-to-stage2-convergence=NOT_PROVEN"
    echo "  eventual-root-removability=YES_IF_CANONICAL_REBUILDS_IT"
    echo "  recommended-root-artifact=$candidate_e_artifact"
    echo "  root-regeneration-path=$candidate_e_regen"
    echo "  reason=$candidate_e_reason"
    echo "candidate=F-reduced-canonical-compiler-bootstrap-slice"
    echo "  viability=$candidate_f_viability"
    echo "  risk=$candidate_f_risk"
    echo "  non-circular=YES_IF_SLICE_COMPILED_BY_EXISTING_ROOT"
    echo "  semantic-authority-source=reduced-canonical-source"
    echo "  trusted-code-size=small-to-medium"
    echo "  canonical-equivalence=REQUIRES_SLICE_TO_FULL_CONVERGENCE"
    echo "  reproducibility=PARTIAL"
    echo "  cross-platform-bootstrap=PARTIAL"
    echo "  artifact-reviewability=YES"
    echo "  stage1-generation-capability=PARTIAL"
    echo "  stage1-to-stage2-convergence=NOT_PROVEN"
    echo "  eventual-root-removability=YES_IF_SLICE_IS_SUBSUMED_BY_CANONICAL"
    echo "  recommended-root-artifact=$candidate_f_artifact"
    echo "  root-regeneration-path=$candidate_f_regen"
    echo "  reason=$candidate_f_reason"
    echo "recommended-root-strategy=$recommended_strategy"
    echo "recommended-root-artifact=$recommended_artifact"
    echo "root-regeneration-path=$root_regeneration_path"
    echo "mandatory-final-gate=canonical-selfhost-convergence-check"
    echo "final-gate-requires=stage1-produced-by-bootstrap-root"
    echo "final-gate-requires=stage2-produced-by-canonical-stage1"
    echo "final-gate-requires=stage3-produced-by-canonical-stage2"
    echo "final-gate-requires=stage2-stage3-semantic-equivalence"
    echo "final-gate-requires=bootstrap-root-runtime-authority-after-stage1-NONE"
    echo "audit-verdict=COMPLETE"
} >"$report"

cat "$report"
