#!/usr/bin/env bash
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
ROOT="$(cd "$SCRIPT_DIR/../.." && pwd)"
SRC="$ROOT/src/runtime/process_runner.c"
MAIN_SRC="$ROOT/src/runtime/process_runner_main.c"
LAUNCHER_LIB_SRC="$ROOT/src/runtime/launcher_lib.c"
LAUNCHER_SRC="$ROOT/src/runtime/launcher.c"
CORE_INTRINSICS_SRC="$ROOT/src/runtime/intrinsics_core.c"
HOST_INTRINSICS_SRC="$ROOT/src/runtime/host_intrinsics.c"
HOST_FS_SRC="$ROOT/src/runtime/host_fs.c"
HOST_PROCESS_SRC="$ROOT/src/runtime/host_process.c"
OUT_LIB="${1:-$ROOT/src/runtime/libprocess_runner.so}"
OUT_BIN="${2:-$ROOT/src/runtime/process_runner}"
OUT_LAUNCHER="${3:-$ROOT/src/runtime/launcher}"
OUT_LAUNCHER_LIB="${4:-$ROOT/src/runtime/liblauncher.so}"
OUT_CORE_LIB="${5:-$ROOT/src/runtime/libintrinsics_core.so}"
OUT_HOST_LIB="${6:-$ROOT/src/runtime/libhost_intrinsics.so}"
OUT_FS_LIB="${7:-$ROOT/src/runtime/libhost_fs.so}"
OUT_PROCESS_LIB="${8:-$ROOT/src/runtime/libhost_process.so}"

gcc -shared -fPIC -O2 -o "$OUT_LIB" "$SRC"
gcc -O2 -o "$OUT_BIN" "$MAIN_SRC" "$SRC"
gcc -shared -fPIC -O2 -o "$OUT_LAUNCHER_LIB" "$LAUNCHER_LIB_SRC" "$SRC"
gcc -O2 -DPROCESS_RUNNER_EXECUTABLE_PATH="\"$OUT_BIN\"" -o "$OUT_LAUNCHER" "$LAUNCHER_SRC"
gcc -shared -fPIC -O2 -o "$OUT_CORE_LIB" "$CORE_INTRINSICS_SRC"
gcc -shared -fPIC -O2 -o "$OUT_HOST_LIB" "$HOST_INTRINSICS_SRC"
gcc -shared -fPIC -O2 -o "$OUT_FS_LIB" "$HOST_FS_SRC"
gcc -shared -fPIC -O2 -o "$OUT_PROCESS_LIB" "$HOST_PROCESS_SRC" "$SRC"
echo "built process runner library: $OUT_LIB"
echo "built process runner executable: $OUT_BIN"
echo "built launcher executable: $OUT_LAUNCHER"
echo "built launcher library: $OUT_LAUNCHER_LIB"
echo "built intrinsic core library: $OUT_CORE_LIB"
echo "built host intrinsics library: $OUT_HOST_LIB"
echo "built host fs library: $OUT_FS_LIB"
echo "built host process library: $OUT_PROCESS_LIB"
