package std.training_io

use std.tensor_core as T

struct CheckpointMeta {
    string format_version
    string framework
    string timestamp
    string s_compiler_version
}

struct TrainState {
    int global_step
    float current_loss
    float best_loss
    int best_step
    bool training_complete
    float[] loss_history

    float grad_norm
    float learning_rate
    int epoch_time_ms
    int total_time_ms
    float tokens_per_second
}

struct ModelConfigSnapshot {
    int vocab_size
    int embed_dim
    int num_heads
    int ffn_dim
    int num_layers
    int max_seq_len
    float dropout_prob

    int total_param_count
    int trainable_param_count
}

struct checkpoint {
    CheckpointMeta meta
    TrainState state
    ModelConfigSnapshot config

    Map<string, T.Tensor> weight_map

    string file_path
    long file_size_bytes
    string checksum_md5
}

func default_meta() CheckpointMeta {
    CheckpointMeta {
        format_version: "2.0",
        framework: "S-AI-Lib-v1.0",
        timestamp: _get_timestamp(),
        s_compiler_version: "1.0-enhanced"
    }
}

func initial_train_state() TrainState {
    TrainState {
        global_step: 0,
        current_loss: 5.0,
        best_loss: 5.0,
        best_step: 0,
        training_complete: false,
        loss_history: new float[20],
        grad_norm: 0.0,
        learning_rate: 0.001,
        epoch_time_ms: 0,
        total_time_ms: 0,
        tokens_per_second: 0.0,
    }
}

func make_config_snapshot(int vocab, int embed, int heads, int ffn, 
                            int layers, int seq_len, float dropout, int total_params) ModelConfigSnapshot {
    ModelConfigSnapshot {
        vocab_size: vocab,
        embed_dim: embed,
        num_heads: heads,
        ffn_dim: ffn,
        num_layers: layers,
        max_seq_len: seq_len,
        dropout_prob: dropout,
        total_param_count: total_params,
        trainable_param_count: total_params,
    }
}

func serialize_checkpoint(checkpoint ckpt) string {
    string content = ""

    content = content + "# ============================================\n"
    content = content + "# NeurX checkpoint v2\n"
    content = content + "# Generated by S Language AI Runtime\n"
    content = content + "# Framework: " + ckpt.meta.framework + "\n"
    content = content + "# ============================================\n\n"

    content = content + "[metadata]\n"
    content = content + "format_version=" + ckpt.meta.format_version + "\n"
    content = content + "framework=" + ckpt.meta.framework + "\n"
    content = content + "timestamp=" + ckpt.meta.timestamp + "\n"
    content = content + "s_version=" + ckpt.meta.s_compiler_version + "\n\n"

    content = content + "[training]\n"
    content = content + "step=" + int_to_str(ckpt.state.global_step) + "\n"
    content = content + "loss=" + fmt_float(ckpt.state.current_loss, 8) + "\n"
    content = content + "best_loss=" + fmt_float(ckpt.state.best_loss, 8) + "\n"
    content = content + "best_step=" + int_to_str(ckpt.state.best_step) + "\n"
    content = content + "completed=" + bool_to_str(ckpt.state.training_complete) + "\n"
    content = content + "grad_norm=" + fmt_float(ckpt.state.grad_norm, 6) + "\n"
    content = content + "learning_rate=" + fmt_float(ckpt.state.learning_rate, 8) + "\n"
    content = content + "total_time_ms=" + int_to_str(ckpt.state.total_time_ms) + "\n"
    content = content + "throughput=" + fmt_float(ckpt.state.tokens_per_second, 1) + "\n"

    content = content + "loss_history=["
    int i = 0
    while i < len(ckpt.state.loss_history) {
        if i > 0 { content = content + ", " }
        content = content + fmt_float(ckpt.state.loss_history[i], 4)
        i = i + 1
    }
    content = content + "]\n\n"

    content = content + "[model_config]\n"
    content = content + "vocab_size=" + int_to_str(ckpt.config.vocab_size) + "\n"
    content = content + "embed_dim=" + int_to_str(ckpt.config.embed_dim) + "\n"
    content = content + "num_heads=" + int_to_str(ckpt.config.num_heads) + "\n"
    content = content + "ffn_dim=" + int_to_str(ckpt.config.ffn_dim) + "\n"
    content = content + "num_layers=" + int_to_str(ckpt.config.num_layers) + "\n"
    content = content + "max_seq_len=" + int_to_str(ckpt.config.max_seq_len) + "\n"
    content = content + "dropout=" + fmt_float(ckpt.config.dropout_prob, 3) + "\n"
    content = content + "total_params=" + int_to_str(ckpt.config.total_param_count) + "\n\n"

    content = content + "[weights]\n"
    for name, tensor in ckpt.weight_map {
        content = content + name + ".shape=["
        int d = 0
        while d < tensor.shape.ndim {
            if d > 0 { content = content + "," }
            content = content + int_to_str(tensor.shape.dims[d])
            d = d + 1
        }
        content = content + "]\n"

        content = content + name + ".data="
        int n = tensor.shape.size
        if n > 100 {
            int p = 0
            while p < 10 {
                content = content + fmt_float(tensor.data[p], 6)
                if p < n - 1 { content = content + "," }
                p = p + 1
            }
            content = content + "...(" + int_to_str(n - 20) + " more)..."
            p = n - 10
            while p < n {
                content = content + fmt_float(tensor.data[p], 6)
                if p < n - 1 { content = content + "," }
                p = p + 1
            }
        } else {
            int p = 0
            while p < n {
                content = content + fmt_float(tensor.data[p], 6)
                if p < n - 1 { content = content + "," }
                p = p + 1
            }
        }
        content = content + "\n"
    }
    content = content + "\n"

    content = content + "# End of checkpoint\n"

    content
}

func save_checkpoint(checkpoint ckpt, string output_dir, string name_prefix) string {
    string filename = name_prefix + "_" + int_to_str(ckpt.state.global_step) + ".neurx"
    string filepath = output_dir + "/" + filename

    string content = serialize_checkpoint(ckpt)

    var result = _write_file(filepath, content)

    if result_is_ok(result) {
        ckpt.file_path = filepath
        println("  [OK] Saved: " + filepath)
        return filepath
    } else {
        println("  [ERR] Failed to save: " + filepath)
        return ""
    }
}

func quick_save(string output_dir, int step, float loss, float best_loss, int best_step,
                 ModelConfigSnapshot config, Map<string, T.Tensor> weights,
                 float[] recent_losses) string {
    checkpoint ckpt
    ckpt.meta = default_meta()
    ckpt.state.global_step = step
    ckpt.state.current_loss = loss
    ckpt.state.best_loss = best_loss
    ckpt.state.best_step = best_step
    ckpt.state.loss_history = recent_losses
    ckpt.config = config
    ckpt.weight_map = weights

    save_checkpoint(ckpt, output_dir, "step")
}

func load_checkpoint(string filepath) checkpoint {
    checkpoint ckpt
    ckpt.file_path = filepath

    var result = _read_file(filepath)
    if !result_is_ok(result) {
        println("[ERR] Cannot load checkpoint: " + filepath)
        return ckpt
    }

    string content = get_result_string(result)

    ckpt.state.global_step = parse_int_field(content, "step", 0)
    ckpt.state.current_loss = parse_float_field(content, "loss", 5.0)
    ckpt.state.best_loss = parse_float_field(content, "best_loss", 5.0)
    ckpt.state.best_step = parse_int_field(content, "best_step", 0)

    ckpt.config.vocab_size = parse_int_field(content, "vocab_size", 256)
    ckpt.config.embed_dim = parse_int_field(content, "embed_dim", 128)
    ckpt.config.num_heads = parse_int_field(content, "num_heads", 4)
    ckpt.config.num_layers = parse_int_field(content, "num_layers", 4)
    ckpt.config.total_param_count = parse_int_field(content, "total_params", 0)

    println("  [OK] Loaded checkpoint from: " + filepath)

    ckpt
}

func load_training_state(string filepath) TrainState {
    checkpoint ckpt = load_checkpoint(filepath)
    ckpt.state
}

func update_manifest(string manifest_path, string new_ckpt_path) void {
    string existing = ""
    var r = _read_file(manifest_path)
    if result_is_ok(r) { existing = get_result_string(r) }

    string updated = existing
    if len(existing) > 0 && !ends_with(existing, "\n") { updated = updated + "\n" }
    updated = updated + new_ckpt_path + "\n"

    _write_file(manifest_path, updated)
}

func list_checkpoints(string manifest_path) string[] {
    var r = _read_file(manifest_path)
    if !result_is_ok(r) { return new string[0] }
    string content = get_result_string(r)

    string[] paths = split_lines(content)
    paths
}

func get_latest_checkpoint(string manifest_path) string {
    string[] cpts = list_checkpoints(manifest_path)
    if len(cpts) == 0 { return "" }
    cpts[len(cpts) - 1]
}

func export_weights(AG.AGTensor[] params) Map<string, T.Tensor> {
    Map<string, T.Tensor> wmap = new_map()
    int i = 0
    while i < len(params) {
        map_put(wmap, params[i].name, params[i].data)
        i = i + 1
    }
    wmap
}

func import_weights(Map<string, T.Tensor> wmap, AG.AGTensor[] mut params) void {
    int i = 0
    while i < len(params) {
        if params[i].name in wmap {
            params[i].data = wmap[params[i].name]
        }
        i = i + 1
    }
}

func export_weights_binary(AG.AGTensor[] params, string output_path) string {
    Map<string, T.Tensor> wmap = export_weights(params)

    checkpoint dummy
    dummy.meta = default_meta()
    dummy.state = initial_train_state()
    dummy.config = make_config_snapshot(0, 0, 0, 0, 0, 0, 0.0, 0)
    dummy.weight_map = wmap

    string content = serialize_checkpoint(dummy)
    _write_file(output_path, content)
    output_path
}

struct TrainingLogEntry {
    int step
    float loss
    float best_loss
    float grad_norm
    float lr
    int elapsed_ms
    string message
}

var _log_entries = new TrainingLogEntry[5000]
var _log_count = 0

func log_entry(int step, float loss, float best_loss, float grad_n, float lr, int ms, string msg) void {
    if _log_count < 5000 {
        _log_entries[_log_count] = TrainingLogEntry {
            step: step, loss: loss, best_loss: best_loss,
            grad_norm: grad_n, lr: lr, elapsed_ms: ms, message: msg
        }
        _log_count = _log_count + 1
    }
}

func save_log(string log_path) void {
    string header = "Step\tLoss\tBestLoss\tGradNorm\tLR\tTime(ms)\tMessage\n"
    string lines = header
    int i = 0
    while i < _log_count {
        TrainingLogEntry e = _log_entries[i]
        lines = lines + int_to_str(e.step) + "\t" +
                 fmt_float(e.loss, 6) + "\t" +
                 fmt_float(e.best_loss, 6) + "\t" +
                 fmt_float(e.grad_norm, 4) + "\t" +
                 fmt_float(e.lr, 8) + "\t" +
                 int_to_str(e.elapsed_ms) + "\t" +
                 e.message + "\n"
        i = i + 1
    }
    _write_file(log_path, lines)
}

func print_log_summary() void {
    println("")
    println("Step |   Loss   |  Best   |  Grad  |    LR    | Time | Note")
    println("-----|----------|---------|--------|----------|------|-----")
    int i = 0
    while i < _log_count {
        TrainingLogEntry e = _log_entries[i]
        string line = pad_int(e.step, 4) + " | " +
                       pad_float(e.loss, 8, 6) + " | " +
                       pad_float(e.best_loss, 7, 6) + " | " +
                       pad_float(e.grad_norm, 5, 4) + " | " +
                       pad_float(e.lr, 7, 8) + " | " +
                       pad_int(e.elapsed_ms, 4) + " | " +
                       e.message
        println(line)
        i = i + 1
    }
}

func _get_timestamp() string {
    "20260623_153000"
}

func int_to_str(int n) string {
    if n == 0 { return "0" }
    bool neg = n < 0
    if neg { n = -n }
    string s = ""
    while n > 0 {
        s = string((n % 10) + 48) + s
        n = n / 10
    }
    if neg { s = "-" + s }
    s
}

func fmt_float(float val, int decimals) string {
    int ival = val as int
    float frac = val - ival as float
    if frac < 0 { frac = -frac }
    string result = int_to_str(ival)
    if decimals > 0 {
        result = result + "."
        int d = 0
        while d < decimals {
            frac = frac * 10.0
            int digit = frac as int
            result = result + int_to_str(digit)
            frac = frac - digit as float
            d = d + 1
        }
    }
    result
}

func bool_to_str(bool b) string {
    if b { "true" } else { "false" }
}

func ends_with(string s, string suffix) bool {
    int slen = len(s)
    int suflen = len(suffix)
    if suflen > slen { return false }
    int i = 0
    while i < suflen {
        if s[slen - suflen + i] != suffix[i] { return false }
        i = i + 1
    }
    true
}

func split_lines(string text) string[] {
    int count = 1
    int i = 0
    while i < len(text) {
        if text[i] == char(10) { count = count + 1 }
        i = i + 1
    }

    string[] result = new string[count]
    string current = ""
    int idx = 0
    i = 0
    while i < len(text) {
        if text[i] == char(10) {
            result[idx] = current
            current = ""
            idx = idx + 1
        } else {
            current = current + string(text[i])
        }
        i = i + 1
    }
    if len(current) > 0 { result[idx] = current }
    result
}

func parse_int_field(string text, string field_name, int default_val) int {
    string target = field_name + "="
    int pos = find_substr(text, target)
    if pos < 0 { return default_val }

    pos = pos + len(target)
    string val_str = ""
    while pos < len(text) {
        char c = text[pos]
        if c == char(10) || c == char(13) || c == char(0) { break }
        val_str = val_str + string(c)
        pos = pos + 1
    }

    int result = 0
    int sign = 1
    int vi = 0
    while vi < len(val_str) {
        char vc = val_str[vi]
        if vc == char(45) { sign = -1 }
        else if vc >= char(48) && vc <= char(57) {
            result = result * 10 + ((vc as int) - 48)
        }
        vi = vi + 1
    }
    result * sign
}

func parse_float_field(string text, string field_name, float default_val) float {
    string target = field_name + "="
    int pos = find_substr(text, target)
    if pos < 0 { return default_val }

    pos = pos + len(target)
    string val_str = ""
    while pos < len(text) {
        char c = text[pos]
        if c == char(10) || c == char(13) || c == char(0) { break }
        val_str = val_str + string(c)
        pos = pos + 1
    }

    float result = 0.0
    float sign = 1.0
    float divisor = 10.0
    bool after_dot = false
    int vi = 0
    while vi < len(val_str) {
        char vc = val_str[vi]
        if vc == char(45) { sign = -1.0 }
        else if vc == char(46) { after_dot = true }
        else if vc >= char(48) && vc <= char(57) {
            int digit = (vc as int) - 48
            if after_dot { result = result + digit as float / divisor; divisor = divisor * 10.0 }
            else { result = result * 10.0 + digit as float }
        }
        vi = vi + 1
    }
    result * sign
}

func find_substr(string haystack, string needle) int {
    int hlen = len(haystack)
    int nlen = len(needle)
    if nlen == 0 { return 0 }
    if nlen > hlen { return -1 }

    int i = 0
    while i <= hlen - nlen {
        bool found = true
        int j = 0
        while j < nlen {
            if haystack[i+j] != needle[j] { found = false; break }
            j = j + 1
        }
        if found { return i }
        i = i + 1
    }
    -1
}

func pad_int(int n, int width) string {
    string s = int_to_str(n)
    while len(s) < width { s = " " + s }
    s
}

func pad_float(float val, int width, int decimals) string {
    string s = fmt_float(val, decimals)
    while len(s) < width { s = " " + s }
    s
}

extern "intrinsic" func __host_write_text_file(string path, string contents) int
extern "intrinsic" func __host_read_to_string(string path) string
extern "intrinsic" func __host_file_exists(string path) int

func _write_file(string path, string content) WriteResult {
    int ret = __host_write_text_file(path, content)
    WriteResult { ok: ret >= 0, error_code: ret }
}

func _read_file(string path) ReadResult {
    if __host_file_exists(path) == 0 {
        return ReadResult { ok: false, data: "", error: "file not found" }
    }
    string data = __host_read_to_string(path)
    ReadResult { ok: true, data: data, error: "" }
}

struct WriteResult {
    bool ok
    int error_code
}

struct ReadResult {
    bool ok
    string data
    string error
}

func result_is_ok(WriteResult r) bool { r.ok }
func result_is_ok(ReadResult r) bool { r.ok }
func get_result_string(ReadResult r) string { r.data }

func char(int code) string { string(code) }
